import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get/get.dart';
import 'package:qr_flutter/qr_flutter.dart';
import '../bloc/auth/auth_bloc.dart';
import '../bloc/auth/auth_event.dart';
import '../bloc/auth/auth_state.dart';
import '../widgets/auth_text_field.dart';

class MfaSetupPage extends StatefulWidget {
  const MfaSetupPage({super.key});

  @override
  State<MfaSetupPage> createState() => _MfaSetupPageState();
}

class _MfaSetupPageState extends State<MfaSetupPage> {
  final _codeController = TextEditingController();

  @override
  void initState() {
    super.initState();
    context.read<AuthBloc>().add(MfaSetupRequested());
  }

  @override
  void dispose() {
    _codeController.dispose();
    super.dispose();
  }

  void _handleEnable() {
    final code = _codeController.text.trim();
    if (code.length != 6) {
      Get.snackbar('Error', 'Please enter the 6-digit code from your app');
      return;
    }
    context.read<AuthBloc>().add(MfaEnableRequested(code));
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(title: const Text('Setup Multi-Factor Auth')),
      body: BlocListener<AuthBloc, AuthState>(
        listener: (context, state) {
          if (state.status == AuthStatus.authenticated && state.user?.mfaEnabled == true) {
            Get.snackbar('Success', 'MFA enabled successfully');
            Get.back();
          } else if (state.status == AuthStatus.error) {
            Get.snackbar('Error', state.message ?? 'Failed to setup MFA');
          }
        },
        child: BlocBuilder<AuthBloc, AuthState>(
          builder: (context, state) {
            if (state.status == AuthStatus.authenticating && state.mfaSetup == null) {
              return const Center(child: CircularProgressIndicator());
            }

            final setup = state.mfaSetup;
            if (setup == null) {
              return Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text('Failed to load MFA setup info'),
                    const SizedBox(height: 16),
                    ElevatedButton(
                      onPressed: () => context.read<AuthBloc>().add(MfaSetupRequested()),
                      child: const Text('Retry'),
                    ),
                  ],
                ),
              );
            }

            return SingleChildScrollView(
              padding: const EdgeInsets.all(24.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  const Text(
                    '1. Scan the QR Code',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 8),
                  const Text('Scan this code in your authenticator app (Google Authenticator, Authy, etc.)'),
                  const SizedBox(height: 24),
                  Center(
                    child: QrImageView(
                      data: setup.qrCodeUrl,
                      version: QrVersions.auto,
                      size: 200.0,
                    ),
                  ),
                  const SizedBox(height: 24),
                  const Text(
                    'Or enter the secret manually:',
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  SelectableText(
                    setup.secret,
                    textAlign: TextAlign.center,
                    style: const TextStyle(fontSize: 16, letterSpacing: 2),
                  ),
                  const SizedBox(height: 32),
                  const Divider(),
                  const SizedBox(height: 24),
                  const Text(
                    '2. Verify & Enable',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 8),
                  const Text('Enter the 6-digit code generated by your app to confirm setup.'),
                  const SizedBox(height: 24),
                  AuthTextField(
                    controller: _codeController,
                    label: 'Verification Code',
                    hint: '000000',
                    prefixIcon: Icons.security,
                    keyboardType: TextInputType.number,
                  ),
                  const SizedBox(height: 32),
                  ElevatedButton(
                    onPressed: state.status == AuthStatus.authenticating ? null : _handleEnable,
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.all(16),
                    ),
                    child: state.status == AuthStatus.authenticating
                        ? const CircularProgressIndicator(color: Colors.white)
                        : const Text('Enable MFA'),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}
